apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kiii-hello-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kiii-hello-world
    spec:
      containers:
        - name: kiii-hello-world
          image: gcr.io/kiii-devops-project/kiii-hello-world-image:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: kiii-hello-world-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kiii-hello-world